DATABASE:
  class: AppDAF\CORE\Database
  argument: []

CITOYEN_REPOSITORY:
  class: AppDAF\REPOSITORY\CitoyenRepository
  argument:
    - "@DATABASE"

LOG_REPOSITOTY:
  class: AppDAF\REPOSITORY\LogRepository
  argument:
    - "@DATABASE"

CITOYEN_SERVICE:
  class: AppDAF\SERVICE\CitoyenService
  argument:
    - "@CITOYEN_REPOSITORY"

LOG_SERVICE:
  class: AppDAF\SERVICE\LogService
  argument:
    - "@LOG_REPOSITOTY"

CITOYEN_CONTROLLER:
  class: AppDAF\CONTROLLER\CitoyenController
  argument:
    - "@CITOYEN_SERVICE"
    - "@LOG_SERVICE"

ERROR_CONTROLLER:
  class: AppDAF\CONTROLLER\ErrorController
  argument: []

CLOUD_SERVICE:
  class: AppDAF\SERVICE\CloudService
  argument: []
